### ISSUE TITLE
您好 SSL 认证方式我用mqtt.fx客户端一直没认证成功

### ISSUE THREAD

**Issue by lihuazhang323** [joey-happy/jo-mqtt#17]
能提供下证书制作过程 和客户端该如何配置 吗

**Comment by joey-happy** [comment]
> 能提供下证书制作过程 和客户端该如何配置 吗
您好 这确实是个bug 这两天有点儿忙 估计得过几天才能搞这个了 见谅

**Comment by joey-happy** [comment]
哥们 你看我的readme文件 有一个我的微信二维码 你加我一下 我看看你是怎么配置的

**Comment by lihuazhang323** [comment]
> 哥们 你看我的readme文件 有一个我的微信二维码 你加我一下 我看看你是怎么配置的

![企业微信截图_16599269058241](https://user-images.githubusercontent.com/3085718/183328447-480b3306-5b55-4bd8-9cf1-4f34f15667a9.png)
我也搞不懂用的哪种，我建议参考阿里的一型一密

**Comment by joey-happy** [comment]
1.看一下后端服务日志报什么错误？
2.阿里的一型一密？ 方便发一下参考连接吗？

**Comment by lihuazhang323** [comment]
> 1.看一下后端服务日志报什么错误？ 2.阿里的一型一密？ 方便发一下参考连接吗？

https://help.aliyun.com/document_detail/74006.html
![image](https://user-images.githubusercontent.com/3085718/183337737-c2d76b35-3218-47b2-b86a-0a8c27db0f07.png)

**Comment by joey-happy** [comment]
好的 我先看看啊 最近有些忙

**Comment by lihuazhang323** [comment]
> 好的 我先看看啊 最近有些忙

https://github.com/Hakky54/mutual-tls-ssl  感觉这个有点用

**Comment by joey-happy** [comment]
> 

我先看看吧 应该不会很复杂 就是现在要开发需求 没时间搞  希望不要影响你的使用 哈哈
