### ISSUE TITLE
请问一下

### ISSUE THREAD

**Issue by mihutao111** [joey-happy/jo-mqtt#27]
您好，我想请问一下怎么配置clientID和username和password.我用弄提供的通信猫连接报错.
![image](https://github.com/joey-happy/jo-mqtt/assets/148837897/04a11426-29b8-4679-8721-69e2c7be8bbe)
![image](https://github.com/joey-happy/jo-mqtt/assets/148837897/3ccf69e1-8cf4-4380-a8a3-9a0e519c448f)

**Comment by joey-happy** [comment]
看看readme文件，用户名：local 密码：local
